# Generated by Django 3.0.5 on 2020-04-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20200426_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotice',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='likenotice',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='likenoticecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likenoticecomment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LikeNotice',
        ),
        migrations.DeleteModel(
            name='LikeNoticeComment',
        ),
    ]
