# Generated by Django 3.0.5 on 2020-04-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200426_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
    ]
