# Generated by Django 3.0.5 on 2020-04-26 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qnas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeqnacomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.Comment'),
        ),
        migrations.AddField(
            model_name='likeqnacomment',
            name='comment_liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_qna_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeqna',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.Qna'),
        ),
        migrations.AddField(
            model_name='likeqna',
            name='qna_liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_qna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.Qna'),
        ),
    ]
