# Generated by Django 3.0.5 on 2020-04-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0002_auto_20200426_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='likeqna',
            old_name='qna_liked_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='likeqnacomment',
            old_name='comment_liked_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='author',
            new_name='owner',
        ),
    ]
