# Generated by Django 3.0.5 on 2020-04-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0003_auto_20200426_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qnas.Qna'),
        ),
        migrations.AlterField(
            model_name='likeqna',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qnas.Qna'),
        ),
        migrations.AlterField(
            model_name='likeqnacomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qnas.Comment'),
        ),
    ]
